query getContact ($contactId: ID!) {
  uiapi {
    query {
      Contact(
        where: { Id: { eq: $contactId } }
      ) {
        edges {
          node {
            Id
            Name @optional { value }
            Email @optional { value }
            AccountId @optional { value }
            Title @optional { value }

            Account @optional {
              Name @optional {
                value
              }

              Industry @optional {
                value
              }

              Phone @optional {
                value
                displayValue
              }
            }

            Cases @optional {
              edges {
                node {
                  Id
                  CaseNumber @optional {
                    value
                  }

                  Subject @optional {
                    value
                  }

                  Status @optional {
                    value
                  }

                  Priority @optional {
                    value
                  }
                }
              }
            }

          }
        }
      }
    }
  }
}